name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-22.04 # Ubuntu sürümünü belirleyelim
    timeout-minutes: 5

    steps:
      # Git kullanıcı adı ve e-posta bilgisi ayarlanıyor
      - name: Set up Git user
        run: |
          git config --global user.name "Meczup07"
          git config --global user.email "elifyucel59@gmail.com"

      # Snake animasyonunun oluşturulması
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      # GitHub Pages'e svg dosyasının push edilmesi
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
