name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Snake.svg oluşturuluyor
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Meczup07
          outputs: dist/snake.svg

      # Snake.svg dosyası output branch'ine pushlanıyor
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{PERSONAL_ACCESS_TOKEN}}
